jobs:
  include:
    - language: java
      jdk: openjdk11
      script:
        - cd server
        - ./gradlew build

    - language: node_js
      node_js: 10
      script:
        - cd client
        - npm install
        - npm run test
