jobs:
  include:
    - language: java
      jdk: openjdk8
      script:
        - cd server
        - mvn clean package

    - language: node_js
      node_js: 10
      script:
        - cd client
        - npm install
        - npm run test
